"""suuniq name and surname

Revision ID: 3683598e6dc3
Revises: ce60a690ec95
Create Date: 2023-08-12 21:16:26.553369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3683598e6dc3'
down_revision = 'ce60a690ec95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.create_unique_constraint('fullname', ['name', 'surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_model', schema=None) as batch_op:
        batch_op.drop_constraint('fullname', type_='unique')

    # ### end Alembic commands ###
